[package]
name = "brainhat"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
bincode = "1.3.3"
byteorder = "1.5.0"
rppal = "0.22.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
